name: Run tests workflow

env:
  GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
  
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: yarn
      - run: yarn test
